In [2]:
import numpy as np

Array

The array object in NumPy is called ndarray
We can create a NumPy ndarray object by using the array() function

In [14]:
# list to create NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr[0])
print(type(arr))    # is a python built-in func. that tell the type of object

[1 2 3 4 5]
1
<class 'numpy.ndarray'>


In [13]:
# tuple to craete NumPy array
arrt = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [12]:
# 2-D array
arrd = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr.ndim)  # dimention

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [15]:
# array slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


In [17]:
fruits = np.array(['apple', 'banana', 'orange'])
print(fruits)
print(fruits.dtype)

['apple' 'banana' 'orange']
<U6


In [19]:
# Change data type
arr = np.array([1.1, 2.1, 3.1])
print(arr)
newarr = arr.astype(int)
print(newarr)

[1.1 2.1 3.1]
[1 2 3]


In [23]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
print(x)
arr[0] = 10
x[0] = 20
print(arr)
print(x)

[1 2 3 4 5]
[10  2  3  4  5]
[20  2  3  4  5]


In [25]:
# Make a view, change the original array, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

arr[0] = 10
x[0] = 20

print(arr)
print(x)

[20  2  3  4  5]
[20  2  3  4  5]


In [26]:
a = np.array([1, 2, 3, 4, 5])
s = a.sum()
print(s)

15


In [28]:
# variance of an array -> it quantifies how much the values differ from the mean (average) of the values
v = a.var()
print(v)

2.0


In [29]:
print(a.mean())

3.0


In [31]:
# standard deviation -> a measure of the amount of variation or dispersion of a set of values. It is the square root of the variance
print(a.std())

1.4142135623730951


In [33]:
ar = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

print(ar.sum())  # sums all the elements
print(ar.sum(axis=0))  # vertical sum
print(ar.sum(axis=1))  # horizontal sum

45
[12 15 18]
[ 6 15 24]


In [34]:
l = [0, 1, 2, 3, 4]

[i*10 for i in l]

[0, 10, 20, 30, 40]

In [49]:
arr = np.array([1, 2, 3, 4])
for i in l:
    print(i)

0
1
2
3
4


In [51]:
# NumPy Array
# For numerical computations and performance-critical applications, NumPy arrays are typically preferred.
# same data type
arr = np.array([1, 2, 3, 4])

# Python list
# For general-purpose use and when working with mixed data types
# mixed data type
l = [1, 2, "Hello", True]

In [36]:
# arange method creates an array with a sequence of numbers. By default, it starts from 0 and increments by 1
a = np.arange(4)
print(a)

[0 1 2 3]


Random Numbers
NumPy offers the random module to work with random numbers

In [37]:
from numpy import random

In [41]:
# Generate a random integer from 0 to 100
x = random.randint(100)
print(x)

3


In [44]:
# Generate a random float from 0 to 1
# rand() method returns a random float between 0 and 1
x = random.rand()
print(x)

0.6443391865179995


In [46]:
# Generate a 1-D array containing 5 random integers from 0 to 100
x = random.randint(100, size=(5))
print(x)

[ 9 49 45 73 18]


In [48]:
# Generate a 1-D array containing 5 random floats
x = random.rand(5)
print(x)

[0.19396687 0.24762472 0.61703561 0.85424557 0.54236829]


Array Join

In [54]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
con = np.concatenate((arr1, arr2))  # double ()
print(con)

[1 2 3 4 5 6]


In [56]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
st = np.stack((arr1, arr2), axis=1)  # double ()
print(st)

[[1 4]
 [2 5]
 [3 6]]


In [59]:
h = np.hstack((arr1, arr2))
print(h)

v = np.vstack((arr1, arr2))
print(v)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Split

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
s = np.array_split(arr, 2)
print(s)     # list containing arrays

[array([1, 2, 3]), array([4, 5, 6])]


In [4]:
print(s[0])

[1 2 3]


Search
To search an array, use the where() method, return indexes

In [8]:
# Find the indexes where the value is 4
arr = np.array([1, 2, 3, 4, 5, 4])
s = np.where(arr == 4)
print(s)      # tuple containing array

(array([3, 5], dtype=int64),)


In [9]:
# Find the indexes where the values are even
even = np.where(arr%2 == 0)
print(even)

(array([1, 3, 5], dtype=int64),)


searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted
to maintain the search order.
The searchsorted() method is assumed to be used on sorted arrays.

In [16]:
arr = np.array([5, 6, 7, 8])
s = np.searchsorted(arr, 7)    # (arr, value)
print(s)    # index

2


In [18]:
# searh from right side
arr = np.array([5, 6, 7, 8])
s = np.searchsorted(arr, 7, side='right')   
print(s)

3


In [14]:
arr = np.array([5, 6, 7, 8])
s = np.searchsorted(arr, [4, 9])   # multiple values
print(s)

[0 4]


Sort
sort() method returns a copy of the array, leaving the original array unchanged.

In [19]:
arr = np.array([6, 9, 2, 7, 1])
x = np.sort(arr)
print(x)

[1 2 6 7 9]


In [20]:
arr = np.array([True, False, True])
x = np.sort(arr)
print(x)

[False  True  True]


In [21]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


Filter
In NumPy, you filter an array using a boolean index list.
A boolean index list is a list of booleans corresponding to indexes in the array.

In [24]:
# Create a filter array that will return only even elements from the original array
arr = np.array([6, 9, 2, 7, 1])
even_mask = arr%2 == 0
print(even_mask)
even_num = arr[even_mask]
print(even_num)

[ True False  True False False]
[6 2]
